image: node:6.11.1

cache:
  paths:
  - node_modules/

stages:
  - production

production:
  type: deploy
  stage: production
  environment:
    name: prod
    url: https://$HEROKU_APP_NAME.herokuapp.com
  script:
    - git config --global user.email "barkhaagnihotri5@gmail.com"
    - git config --global user.name "Barkha"
    - git add -f . && git commit -m "updated app"
    - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  only:
    - master